spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AuthDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: mysecretkey
  jwtExpirationInMs: 3600000

cors:
  allowedOrings: '*'
server.port: 8081

