app:
  jwtSecret: mysecretkey
  jwtExpirationInMs: 3600000
  host-auth: localhost
  host-discovery: localhost
spring:
 application:
  name: PIZZA-SERVICE
 config:
  import:optional:configserver:
 cloud:
  config:
   uri: http://${app.host-config}:8888

cors:
  allowedOrings: '*'