app:
  jwtSecret: mysecretkey
  jwtExpirationInMs: 3600000
  host-auth: localhost
  host-product: localhost
  host-discovery: localhost
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CartDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  application:
    name: CART-SERVICE
  config:
    import:optional:configserver:
  cloud:
    config:
      uri: http://${app.host-config}:8888


cors:
  allowedOrings: '*'
server.port: 8082
resilience4j.retry:
    instances:
        pizza:
            registerHealthIndicator: true
            maxAttempts: 5
            waitDuration: 10s


resilience4j.circuitbreaker:
  instances:
    pizza:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      failureRateThreshold: 70
      #minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 2000
      automaticTransitionFromOpenToHalfOpenEnabled: true
      
resilience4j.ratelimiter:
  instances:
    pizza:
      limitRefreshPeriod: 24s
      limitForPeriod: 5
      timeoutDuration: 20s
      registerHealthIndicator: true


management:
  endpoint:
    health:
      show-details: always         #To show all details in /health endpoint.

management.health.circuitbreakers.enabled: true

